/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ulp.trabajopracticonro6;

import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class GestionProductos extends javax.swing.JInternalFrame {

    private GestorProductos gestor;
    private int codigoSeleccionado;

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos(GestorProductos gestor) {
        initComponents();

        this.gestor = gestor;

        celdaspinner_stock.setModel(
                new javax.swing.SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1)
        );

        celdaspinner_stock.setModel(
                new javax.swing.SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1)
        );

        tabla_busqueda.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Codigo", "Descripción", "Precio", "Categoria", "Stock"
                }
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        });

        boton_guardar.setEnabled(false);
        boton_actualizar.setEnabled(false);
        boton_eleminar.setEnabled(false);
        boton_buscar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo_gestion = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_busqueda = new javax.swing.JTable();
        panel_busqueda = new javax.swing.JPanel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        celda_descripcion = new javax.swing.JTextField();
        celda_precio = new javax.swing.JTextField();
        celda_codigo = new javax.swing.JTextField();
        celdabox_rubro = new javax.swing.JComboBox<>();
        celdaspinner_stock = new javax.swing.JSpinner();
        combobox_filtrar = new javax.swing.JComboBox<>();
        boton_cerrar = new javax.swing.JButton();
        boton_buscar = new javax.swing.JButton();
        boton_nuevo = new javax.swing.JButton();
        boton_guardar = new javax.swing.JButton();
        boton_actualizar = new javax.swing.JButton();
        boton_eleminar = new javax.swing.JButton();

        titulo_gestion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_gestion.setText("Gestión de Productos");
        titulo_gestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        texto1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        texto1.setText("Filtrar por Categoria:");

        tabla_busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripción", "Precio", "Categoria", "Stock"
            }
        ));
        tabla_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_busquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_busqueda);

        panel_busqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        texto2.setText("Codigo:");

        texto3.setText("Descripción:");

        texto4.setText("Precio:");

        texto5.setText("Rubro:");

        texto6.setText("Stock:");

        celda_descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                celda_descripcionFocusLost(evt);
            }
        });
        celda_descripcion.addActionListener(this::celda_descripcionActionPerformed);
        celda_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celda_descripcionKeyTyped(evt);
            }
        });

        celda_precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                celda_precioFocusLost(evt);
            }
        });
        celda_precio.addActionListener(this::celda_precioActionPerformed);
        celda_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celda_precioKeyTyped(evt);
            }
        });

        celda_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                celda_codigoFocusLost(evt);
            }
        });
        celda_codigo.addActionListener(this::celda_codigoActionPerformed);
        celda_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celda_codigoKeyTyped(evt);
            }
        });

        celdabox_rubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Comestible", "Limpieza", "Perfumería" }));

        javax.swing.GroupLayout panel_busquedaLayout = new javax.swing.GroupLayout(panel_busqueda);
        panel_busqueda.setLayout(panel_busquedaLayout);
        panel_busquedaLayout.setHorizontalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busquedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_busquedaLayout.createSequentialGroup()
                        .addComponent(texto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(celda_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_busquedaLayout.createSequentialGroup()
                        .addComponent(texto3)
                        .addGap(34, 34, 34)
                        .addComponent(celda_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_busquedaLayout.createSequentialGroup()
                        .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_busquedaLayout.createSequentialGroup()
                                    .addComponent(texto4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_busquedaLayout.createSequentialGroup()
                                    .addComponent(texto5)
                                    .addGap(65, 65, 65)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_busquedaLayout.createSequentialGroup()
                                .addComponent(texto6)
                                .addGap(68, 68, 68)))
                        .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celdaspinner_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(celda_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(celdabox_rubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        panel_busquedaLayout.setVerticalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busquedaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto2)
                    .addComponent(celda_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto3)
                    .addComponent(celda_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto4)
                    .addComponent(celda_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celdabox_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto6)
                    .addComponent(celdaspinner_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        combobox_filtrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Comestible", "Limpieza", "Perfumería" }));
        combobox_filtrar.addActionListener(this::combobox_filtrarActionPerformed);

        boton_cerrar.setText("Cerrar");
        boton_cerrar.addActionListener(this::boton_cerrarActionPerformed);

        boton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        boton_buscar.addActionListener(this::boton_buscarActionPerformed);

        boton_nuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevo.png"))); // NOI18N
        boton_nuevo.setText("Nuevo");
        boton_nuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_nuevo.setOpaque(true);
        boton_nuevo.addActionListener(this::boton_nuevoActionPerformed);

        boton_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar.png"))); // NOI18N
        boton_guardar.setText("Guardar");
        boton_guardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar.setOpaque(true);
        boton_guardar.addActionListener(this::boton_guardarActionPerformed);

        boton_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar.png"))); // NOI18N
        boton_actualizar.setText("Actualizar");
        boton_actualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_actualizar.setOpaque(true);
        boton_actualizar.addActionListener(this::boton_actualizarActionPerformed);

        boton_eleminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_eleminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrar.png"))); // NOI18N
        boton_eleminar.setText("Eliminar");
        boton_eleminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boton_eleminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_eleminar.setOpaque(true);
        boton_eleminar.addActionListener(this::boton_eleminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boton_cerrar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(texto1)
                                .addGap(18, 18, 18)
                                .addComponent(combobox_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(titulo_gestion)
                                .addGap(60, 60, 60)))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_eleminar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_gestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(boton_cerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_eleminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celda_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celda_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celda_descripcionActionPerformed

    private void celda_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celda_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celda_precioActionPerformed

    private void celda_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celda_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celda_codigoActionPerformed

    private void boton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevoActionPerformed
        // TODO add your handling code here:
        celda_codigo.setText("");
        celda_descripcion.setText("");
        celda_precio.setText("");
        celdabox_rubro.setSelectedIndex(0);
        celdaspinner_stock.setValue(0);

        boton_guardar.setEnabled(true);
        boton_actualizar.setEnabled(false);
        boton_eleminar.setEnabled(false);

        celda_codigo.requestFocus();
    }//GEN-LAST:event_boton_nuevoActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
        // TODO add your handling code here:
        if (celda_codigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el código.");
            celda_codigo.requestFocus();
            return;
        }

        if (celda_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la descripción.");
            celda_descripcion.requestFocus();
            return;
        }

        if (celda_precio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el precio.");
            celda_precio.requestFocus();
            return;
        }

        try {

            int codigo = Integer.parseInt(celda_codigo.getText());
            double precio = Double.parseDouble(celda_precio.getText());
            String descripcion = celda_descripcion.getText().trim();
            String rubro = celdabox_rubro.getSelectedItem().toString();
            int stock = (Integer) celdaspinner_stock.getValue();

            Producto producto = new Producto(
                    codigo,
                    descripcion,
                    precio,
                    rubro,
                    stock
            );

            if (gestor.agregarProducto(producto)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Producto guardado."
                );

                actualizarTabla();

                boton_guardar.setEnabled(false);

                celda_codigo.setText("");
                celda_descripcion.setText("");
                celda_precio.setText("");
                celdabox_rubro.setSelectedIndex(0);
                celdaspinner_stock.setValue(0);

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Ya existe ese código."
                );

                celda_codigo.requestFocus();
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "El código y el precio deben ser números."
            );

            celda_codigo.requestFocus();
        }
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void tabla_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_busquedaMouseClicked
        // TODO add your handling code here:
        int fila = tabla_busqueda.getSelectedRow();

        if (fila >= 0) {

            codigoSeleccionado = Integer.parseInt(
                    tabla_busqueda.getValueAt(fila, 0).toString()
            );

            celda_codigo.setText(tabla_busqueda.getValueAt(fila, 0).toString());
            celda_descripcion.setText(tabla_busqueda.getValueAt(fila, 1).toString());
            celda_precio.setText(tabla_busqueda.getValueAt(fila, 2).toString());
            celdabox_rubro.setSelectedItem(tabla_busqueda.getValueAt(fila, 3).toString());
            celdaspinner_stock.setValue(Integer.parseInt(
                    tabla_busqueda.getValueAt(fila, 4).toString()
            ));

            boton_actualizar.setEnabled(true);
            boton_eleminar.setEnabled(true);
            boton_buscar.setEnabled(true);
        }


    }//GEN-LAST:event_tabla_busquedaMouseClicked

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizarActionPerformed
        // TODO add your handling code here:
        if (celda_codigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar código.");
            celda_codigo.requestFocus();
            return;
        }

        if (celda_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar descripción.");
            celda_descripcion.requestFocus();
            return;
        }

        if (celda_precio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar precio.");
            celda_precio.requestFocus();
            return;
        }

        try {
            int codigo = Integer.parseInt(celda_codigo.getText());
            double precio = Double.parseDouble(celda_precio.getText());
            String descripcion = celda_descripcion.getText().trim();
            String rubro = celdabox_rubro.getSelectedItem().toString();
            int stock = (Integer) celdaspinner_stock.getValue();

            Producto productoViejo = null;

            for (Producto producto : gestor.getProductos()) {
                if (producto.getCodigo() == codigoSeleccionado) {
                    productoViejo = producto;
                    break;
                }
            }

            if (productoViejo != null) {
                gestor.eliminarProducto(productoViejo);
            }

            Producto productoNuevo = new Producto(
                    codigo,
                    descripcion,
                    precio,
                    rubro,
                    stock
            );

            if (gestor.agregarProducto(productoNuevo)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Actualizado."
                );

                actualizarTabla();

                boton_actualizar.setEnabled(false);
                boton_eleminar.setEnabled(false);
                boton_buscar.setEnabled(false);

                celda_codigo.setText("");
                celda_descripcion.setText("");
                celda_precio.setText("");
                celdabox_rubro.setSelectedIndex(0);
                celdaspinner_stock.setValue(0);

            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Ya existe ese código."
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "El código y el precio deben ser números."
            );

            celda_codigo.requestFocus();
    }//GEN-LAST:event_boton_actualizarActionPerformed
    }
    private void boton_eleminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eleminarActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Eliminar el producto?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

            Producto productoEliminar = null;

            for (Producto producto : gestor.getProductos()) {
                if (producto.getCodigo() == codigoSeleccionado) {
                    productoEliminar = producto;
                    break;
                }
            }

            if (productoEliminar != null) {

                gestor.eliminarProducto(productoEliminar);

                JOptionPane.showMessageDialog(
                        this,
                        "Producto eliminado."
                );

                actualizarTabla();

                celda_codigo.setText("");
                celda_descripcion.setText("");
                celda_precio.setText("");
                celdabox_rubro.setSelectedIndex(0);
                celdaspinner_stock.setValue(0);

                boton_actualizar.setEnabled(false);
                boton_eleminar.setEnabled(false);
                boton_buscar.setEnabled(false);
            }
    }//GEN-LAST:event_boton_eleminarActionPerformed
    }
    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
        // TODO add your handling code here:
        String textoCodigo = celda_codigo.getText().trim();

        if (textoCodigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el código.");
            celda_codigo.requestFocus();
            return;
        }

        try {

            int codigo = Integer.parseInt(textoCodigo);

            boolean encontrado = false;

            for (Producto producto : gestor.getProductos()) {

                if (producto.getCodigo() == codigo) {

                    celda_codigo.setText(String.valueOf(producto.getCodigo()));
                    celda_descripcion.setText(producto.getDescripcion());
                    celda_precio.setText(String.valueOf(producto.getPrecio()));
                    celdabox_rubro.setSelectedItem(producto.getRubro());
                    celdaspinner_stock.setValue(producto.getStock());

                    codigoSeleccionado = producto.getCodigo();

                    encontrado = true;

                    boton_actualizar.setEnabled(true);
                    boton_eleminar.setEnabled(true);

                    break;
                }
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(
                        this,
                        "No existe ese código."
                );
                celda_codigo.requestFocus();
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "El código debe ser un número."
            );

            celda_codigo.requestFocus();
    }//GEN-LAST:event_boton_buscarActionPerformed
    }
    private void celda_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celda_codigoKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla)) {
            evt.consume();
        }
    }//GEN-LAST:event_celda_codigoKeyTyped

    private void celda_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celda_precioKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_celda_precioKeyTyped

    private void celda_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celda_descripcionKeyTyped
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();

        if (!Character.isLetterOrDigit(tecla) && tecla != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_celda_descripcionKeyTyped

    private void combobox_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_filtrarActionPerformed
        // TODO add your handg code here
        String rubroSeleccionado
                = combobox_filtrar.getSelectedItem().toString();

        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) tabla_busqueda.getModel();

        modelo.setRowCount(0);

        for (Producto producto : gestor.getProductos()) {

            if (rubroSeleccionado.equals("Todas")
                    || producto.getRubro().equals(rubroSeleccionado)) {

                modelo.addRow(new Object[]{
                    producto.getCodigo(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getRubro(),
                    producto.getStock()
                });
            }
        }
    }//GEN-LAST:event_combobox_filtrarActionPerformed

    private void celda_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celda_codigoFocusLost
        // TODO add your handling code here:
        if (celda_codigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresar código.");
            celda_codigo.requestFocus();
        }
    }//GEN-LAST:event_celda_codigoFocusLost

    private void celda_descripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celda_descripcionFocusLost
        // TODO add your handling code here:
        if (celda_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresar descripción.");
            celda_descripcion.requestFocus();
        }
    }//GEN-LAST:event_celda_descripcionFocusLost

    private void celda_precioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celda_precioFocusLost
        // TODO add your handling code here:
        if (celda_precio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresar el precio.");
            celda_precio.requestFocus();
        }
    }//GEN-LAST:event_celda_precioFocusLost

    private void boton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_cerrarActionPerformed

    private void actualizarTabla() {

        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) tabla_busqueda.getModel();

        modelo.setRowCount(0);

        for (Producto producto : gestor.getProductos()) {

            modelo.addRow(new Object[]{
                producto.getCodigo(),
                producto.getDescripcion(),
                producto.getPrecio(),
                producto.getRubro(),
                producto.getStock()
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_cerrar;
    private javax.swing.JButton boton_eleminar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JButton boton_nuevo;
    private javax.swing.JTextField celda_codigo;
    private javax.swing.JTextField celda_descripcion;
    private javax.swing.JTextField celda_precio;
    private javax.swing.JComboBox<String> celdabox_rubro;
    private javax.swing.JSpinner celdaspinner_stock;
    private javax.swing.JComboBox<String> combobox_filtrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_busqueda;
    private javax.swing.JTable tabla_busqueda;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel titulo_gestion;
    // End of variables declaration//GEN-END:variables

}
