/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ulp.trabajopracticonro6;

/**
 *
 * @author diego
 */
public class ListadoPorRubro extends javax.swing.JInternalFrame {

    private GestorProductos gestor;

    /**
     * Creates new form ListadoPorRubro
     */
    public ListadoPorRubro(GestorProductos gestor) {
        initComponents();
        this.gestor = gestor;

        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) tabla_listadorubro.getModel();

        modelo.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        celdabox_rubro = new javax.swing.JComboBox<>();
        tittle_listadoderubro = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_listadorubro = new javax.swing.JTable();

        setTitle("Listado por Rubro");

        celdabox_rubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Comestible", "Limpieza", "Perfumería" }));
        celdabox_rubro.addActionListener(this::celdabox_rubroActionPerformed);

        tittle_listadoderubro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tittle_listadoderubro.setText("Listado por Rubro");

        text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text2.setText("Rubro:");

        tabla_listadorubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripción", "Precio", "Categoria", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_listadorubro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(tittle_listadoderubro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celdabox_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittle_listadoderubro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2)
                    .addComponent(celdabox_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celdabox_rubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celdabox_rubroActionPerformed
        // TODO add your handling code here:
        String rubroSeleccionado = celdabox_rubro.getSelectedItem().toString();

        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) tabla_listadorubro.getModel();

        modelo.setRowCount(0);

        for (Producto producto : gestor.getProductos()) {

            if (rubroSeleccionado.equals("Todas")
                    || producto.getRubro().equals(rubroSeleccionado)) {

                modelo.addRow(new Object[]{
                    producto.getCodigo(),
                    producto.getDescripcion(),
                    producto.getPrecio(),
                    producto.getRubro(),
                    producto.getStock()
                });
            }
        }
    }//GEN-LAST:event_celdabox_rubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> celdabox_rubro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_listadorubro;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel tittle_listadoderubro;
    // End of variables declaration//GEN-END:variables
}
