/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ulp.trabajopracticonro6;

/**
 *
 * @author diego
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        navbar_principal = new javax.swing.JMenuBar();
        menu_administración = new javax.swing.JMenu();
        item_gestionarproductos = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        item_listardenombres = new javax.swing.JMenuItem();
        item_listardeprecios = new javax.swing.JMenuItem();
        item_listarderubros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Productos");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        menu_administración.setText("Administración");

        item_gestionarproductos.setText("Gestionar Productos");
        menu_administración.add(item_gestionarproductos);

        navbar_principal.add(menu_administración);

        menu_consultas.setText("Consultas");

        item_listardenombres.setText("Listado Por Nombre");
        menu_consultas.add(item_listardenombres);

        item_listardeprecios.setText("Listado Por Precio");
        item_listardeprecios.addActionListener(this::item_listardepreciosActionPerformed);
        menu_consultas.add(item_listardeprecios);

        item_listarderubros.setText("Listado Por Rubro");
        menu_consultas.add(item_listarderubros);

        navbar_principal.add(menu_consultas);

        setJMenuBar(navbar_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_listardepreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_listardepreciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_listardepreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_gestionarproductos;
    private javax.swing.JMenuItem item_listardenombres;
    private javax.swing.JMenuItem item_listardeprecios;
    private javax.swing.JMenuItem item_listarderubros;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu menu_administración;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenuBar navbar_principal;
    // End of variables declaration//GEN-END:variables
}
